: 4REVERSE
   SWAP 2SWAP SWAP ;

CR 1 2 3 4 4REVERSE .S 2DROP 2DROP

: 3DUP
   DUP 2OVER ROT ;

CR 1 2 3 3DUP .S 2DROP 2DROP 2DROP

: FOUR ( C A B -- RESULT )
   SWAP ( C B A )
   DUP DUP ( C B A A A )
   * ( C B A A^2 )
   SWAP ( C B A^2 A )
   ROT ( C A^2 A B )
   * ( C A^2 A*B )
   + + ;

CR 4 2 3 FOUR .

: FIVE ( A B -- RESULT )
   2DUP ( A B A B )
   - ( A B A-B )
   ROT ( B A-B A )
   ROT ( A-B A B )
   + ( A-B A+B )
   / ;

CR 2 1 FIVE .
CR 3 2 FIVE .

: CONVICTED-OF 0 ;
: HOMICIDE 20 + ;
: ARSON 10 + ;
: BOOKMAKING 2 + ;
: TAX-EVASION 5 + ;

: WILL-SERVE
   . ." YEARS" ;

CONVICTED-OF ARSON HOMICIDE TAX-EVASION
WILL-SERVE
CR

: EGG-CARTONS
   12 /MOD CR . ." CARTONS AND " . ." LEFT OVER." ;

12 EGG-CARTONS
24 EGG-CARTONS
5 EGG-CARTONS
25 EGG-CARTONS

