: NOT
   0= ;

CR
CR 1 0= NOT . ." SHOULD BE TRUE"
CR 0 0= NOT . ." SHOULD BE FALSE"
CR 200 0= NOT . ." SHOULD BE TRUE"

: CARD ( N -- )
   18 >= IF
     ." ALCOHOLIC BEVERAGES PERMITTED"
   ELSE
     ." UNDER AGE"
   THEN ;

CR
CR 10 DUP . CARD
CR 17 DUP . CARD
CR 18 DUP . CARD
CR 19 DUP . CARD

: SIGN.TEST ( N -- )
   DUP 0> IF ." POSITIVE" THEN
   DUP 0= IF ." ZERO" THEN
       0< IF ." NEGATIVE" THEN ;

CR
CR ." (SHOULD BE NEGATIVE) " -1 SIGN.TEST
CR ." (SHOULD BE ZERO) " 0 SIGN.TEST
CR ." (SHOULD BE POSITIVE) " 1 SIGN.TEST

: STAR ( -- )
   42 EMIT ;

: STARS ( N -- )
   DUP 0= IF DROP ELSE 0 DO STAR LOOP THEN ;

CR
CR 0 STARS
CR 1 STARS
CR 5 STARS

: WITHIN ( N LOW-LIMIT HIGH-LIMIT -- WITHIN )
   ROT DUP ROT < ( LL N LT )
   ROT ROT < ( LT HT )
   AND ;

CR
CR ." (SHOULD BE TRUE) " 5 4 6 WITHIN .
CR ." (SHOULD BE FALSE) " 4 5 8 WITHIN .

: GUESS ( SECRET GUESS -- SECRET / SECRET GUESS -- )
   2DUP < IF ." TOO HIGH" THEN
   2DUP > IF ." TOO LOW" THEN
   OVER = IF DROP ." SUCCESS!" THEN
   CR ;

: SPELLER ( N -- )
   DUP ABS
   DUP ROT
       = NOT IF ." NEGATIVE " THEN
   DUP 4 = IF ." FOUR" DROP ELSE
   DUP 3 = IF ." THREE" DROP ELSE
   DUP 2 = IF ." TWO" DROP ELSE
   DUP 1 = IF ." ONE" DROP ELSE
       0= IF ." ZERO" DROP ELSE
         ." OUT OF RANGE"
   THEN THEN THEN THEN THEN ;

CR
CR ." (SHOULD BE TWO) " 2 SPELLER
CR ." (SHOULD BE NEGATIVE FOUR) " -4 SPELLER
CR ." (SHOULD BE OUT OF RANGE) " 7 SPELLER

: TRAP ( SECRET LOW HIGH -- SECRET )
   2DUP ( SECRET LOW HIGH LOW HIGH )
   = IF
     ." YOU GOT IT!"
     2DROP DROP ( -- )
   ELSE
     ROT DUP >R
     ROT ROT
     WITHIN IF
       ." BETWEEN "
     ELSE
       ." NOT BETWEEN"
     THEN
     R>
   THEN ;

CR
391
CR ." (SHOULD BE BETWEEN) " 0 1000 TRAP
CR ." (SHOULD BE BETWEEN) " 330 660 TRAP
CR ." (SHOULD BE NOT BETWEEN) " 440 550 TRAP
CR ." (SHOULD BE BETWEEN) " 330 440 TRAP
CR ." (SHOULD BE YOU GOT IT!) " 391 391 TRAP

CR .S
